[package]
name = "unative"
version = "0.2.6"
edition = "2024"
rust-version = "1.95"
description = "Platform-native integer types."
license = "MIT OR Apache-2.0"
authors = ["Tomek Czajka <tczajka@gmail.com>"]
repository = "https://github.com/tczajka/unative"
keywords = ["integer", "native"]
categories = ["hardware-support", "no-std", "no-std::no-alloc"]
include = [
    "src/**/*.rs",
    "tests/**/*.rs",
    "Cargo.toml",
    "README.md",
    "CHANGELOG.md",
    "LICENSE-APACHE",
    "LICENSE-MIT",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
num-traits = ["dep:num-traits"]
proptest = ["dep:proptest"]
rand = ["dep:rand"]
serde = ["dep:serde"]

[dependencies]
num-traits = { version = "0.2.19", default-features = false, optional = true }
proptest = { version = "1.6", default-features = false, features = ["alloc", "no_std"], optional = true }
rand = { version = "0.10", default-features = false, optional = true }
serde = { version = "1.0.60", default-features = false, optional = true }

[dev-dependencies]
unative = { path = ".", features = ["proptest"] }
proptest = { version = "1.6" }
rand = { version = "0.10", default-features = false, features = ["chacha"] }
serde_test = "1.0.127"
