[package]
name = "unative"
version = "0.2.0"
edition = "2024"
rust-version = "1.95"
description = "Platform-native integer types."
license = "MIT OR Apache-2.0"
authors = ["Tomek Czajka <tczajka@gmail.com>"]
repository = "https://github.com/tczajka/unative"
keywords = ["integer", "native", "no-std", "numeric", "platform"]
include = [
    "src/**/*.rs",
    "tests/**/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE-APACHE",
    "LICENSE-MIT",
]

[dependencies]
serde = { version = "1", default-features = false, optional = true }

[dev-dependencies]
serde_test = "1"
